DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID INT NOT NULL AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (DEPARTMENT_ID)
);

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    E_MAIL VARCHAR(50),
    SALARY DOUBLE NOT NULL,
    DEPARTMENT_ID INT,
    PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UNIQUE_NAMES UNIQUE (FIRST_NAME,LAST_NAME),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
